import os
import subprocess
import re

# --- CONFIGURATION ---
C_SOURCE_FILE = "scriptedGrokass.c"      # Ensure this matches your actual C filename
EXECUTABLE_NAME = "fast_miner"           
CHECKER_EXEC = "checker_macos_arm64.out" 
DATASET_FOLDER = "Datasets"              
METRICS_FILE = "metrics.txt"             
THETA = "0.9"                            

# List of your base dataset names
BASE_NAMES = ["apj", "domino", "emea", "hc"]

# Output files generated by the C code
OUT_UA = "UA_TIME.txt"
OUT_PA = "PA_TIME.txt"
OUT_REB = "REB_TIME.txt"

def count_lines(filepath):
    """Helper to count lines in a file."""
    with open(filepath, 'r') as f:
        return sum(1 for _ in f)

def get_metrics_from_files():
    """Calculates |R| and |PA|+|REB| by reading the generated files directly."""
    try:
        # 1. Get |R| from UA file (2nd line of header is |R|)
        with open(OUT_UA, 'r') as f:
            _ = f.readline() # Skip line 1 (num users)
            r_line = f.readline().strip()
            r_val = int(r_line)

        # 2. Get |PA| count (Total lines in PA file - 2 header lines)
        pa_lines = count_lines(OUT_PA)
        pa_count = max(0, pa_lines - 2)

        # 3. Get |REB| count (Total lines in REB file - 1 header line)
        reb_lines = count_lines(OUT_REB)
        reb_count = max(0, reb_lines - 1)

        # 4. Calculate Sum
        pareb_val = pa_count + reb_count
        
        return str(r_val), str(pareb_val)
        
    except Exception as e:
        print(f"      ⚠️ Error reading metrics from files: {e}")
        return "ERR", "ERR"

def get_mismatches(output_text):
    """Extracts the number of mismatches from the checker output string."""
    # Search for "Mismatches: 164" pattern
    match = re.search(r"Mismatches:\s*(\d+)", output_text)
    if match:
        return match.group(1)
    return "N/A"

def main():
    # 1. Compile with OpenMP
    print(f"🔨 Compiling {C_SOURCE_FILE}...")
    compile_cmd = [
        "gcc", C_SOURCE_FILE, "-o", EXECUTABLE_NAME
    ]

    if subprocess.run(compile_cmd).returncode != 0:
        print("❌ Compilation failed!")
        return

    # 2. Initialize Metrics File with NEW COLUMN
    with open(METRICS_FILE, "w") as f:
        # Added 'Mismatch' column width 10
        f.write(f"{'Dataset':<15} {'TimeFile':<40} {'|R|':<10} {'|PA|+|REB|':<15} {'Mismatch':<10} {'Status'}\n")
        f.write("-" * 100 + "\n")

    # 3. Get list of files
    try:
        all_files = os.listdir(DATASET_FOLDER)
    except FileNotFoundError:
        print(f"❌ Error: Folder '{DATASET_FOLDER}' not found.")
        return

    total_runs = 0
    
    # 4. Loop through datasets
    for base in BASE_NAMES:
        base_file = f"{base}.txt"
        time_files = [f for f in all_files if f.startswith("TIME_") and f.endswith(f"_{base}.txt")]
        time_files.sort() 

        print(f"\n=== Processing Dataset: {base} ({len(time_files)} variants) ===")

        for time_file in time_files:
            print(f"   ▶ Running: {base_file} + {time_file}")

            # A. Run C Program
            c_cmd = [f"./{EXECUTABLE_NAME}", THETA, base_file, time_file]
            c_process = subprocess.run(c_cmd) 

            if c_process.returncode != 0:
                print(f"      ❌ C Code Crashed.")
                status = "CRASH_C"
                r_val, pareb_val = "ERR", "ERR"
                mismatches = "ERR"
            else:
                # Calculate metrics from files
                r_val, pareb_val = get_metrics_from_files()

                # B. Run Checker
                path_dataset = os.path.join(DATASET_FOLDER, base_file)
                path_time = os.path.join(DATASET_FOLDER, time_file)
                checker_cmd = [f"./{CHECKER_EXEC}", path_dataset, path_time, OUT_UA, OUT_PA, OUT_REB]
                
                try:
                    # Capture output to parse mismatches
                    check_proc = subprocess.run(checker_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
                    out = check_proc.stdout
                    
                    # Parse mismatch count
                    mismatches = get_mismatches(out)

                    # Determine Status
                    if "VERIFICATION FAILED" in out:
                        status = "FAIL"
                    elif "Mismatches" in out and mismatches != "0":
                        status = "FAIL"
                    elif "SUCCESS" in out or "success" in out:
                        status = "SUCCESS"
                    else:
                        status = "SUCCESS" if check_proc.returncode == 0 else "FAIL"
                        
                except FileNotFoundError:
                     status = "NO_CHECKER"
                     mismatches = "N/A"
                     print(f"      ⚠️ Checker not found!")

            # C. Write to Metrics File
            with open(METRICS_FILE, "a") as f:
                f.write(f"{base:<15} {time_file:<40} {r_val:<10} {pareb_val:<15} {mismatches:<10} {status}\n")

            total_runs += 1

    print(f"\n✅ All done! Processed {total_runs} experiments.")
    print(f"📊 Metrics saved to '{METRICS_FILE}'")

if __name__ == "__main__":
    main()